title: Drift Kasino | DK-BOT 自動下注軟體 | 極速賽車 | 北京賽車 | 幸運飛艇
description: 極速賽車自動下注軟體
author: Drift Kasino
logo: https://i.imgur.com/XY0fNc0.jpg
github: https://github.com/driftkasino
about: DK-BOT 自動下注軟體

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
